### PR TITLE
OpenCL/CPUContext: use the Common ForkJoinPool instead of a FixedThreadPool

### PR DESCRIPTION
**Pull request by andi-huber**
in reference to #462

Renames the former `CPUContext` to `CPUContextUsingFixedThreadPool`. If one want's to use the old one, there is a new CPUPlatform constructor, that allows to override default behavior.

```java
CPUPlatform customCPUPlatform = new CPUPlatform(aLogger, CPUContextUsingFixedThreadPool::new);
```

---
This change is [Reviewable](https://reviewable.io/reviews/mirkosertic/bytecoder/463)

### CODE REVIEW

**Comment by mirkosertic** [comment]
The code looks good, but there are some tests failing. Would you like to fix them?

**Comment by andi-huber** [comment]
Had a look at it yesterday. Unfortunately I don't understand this particular test implementations. Its rather unlikely, that I find time to fix this myself. I'm also fine if this PR gets rejected.

**Comment by mirkosertic** [comment]
Hmm, there is a bug in the tests and the emulation layer preventing them to run in CPU emulation mode. Here is a path to fix this. Would you please review this and include it into this PR?

[Test_fixes.zip](https://github.com/mirkosertic/Bytecoder/files/5277709/Test_fixes.zip)

**Comment by andi-huber** [comment]
Thx! Test Patch seemed to have worked. I've now added another improvement, to allow more fine grained control on automated OpenCL device selection.

The new default behavior is to find the OpenCL device that has the most CUs then use it. Overriding this via system properties should still work.

**Comment by mirkosertic** [comment]
I've squashed the changes into master branch.

Thank you for your contribution!

**Pull request merged**
